version: "3.3"
services:
  traefik:
    image: "traefik:v2.4"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:8090"
    ports:
      - "8090:8090"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  backend1:
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`traefik`) && PathPrefix(`/v1`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.routers.backend.middlewares=remove-v1"
      - "traefik.http.middlewares.remove-v1.stripprefix.prefixes=/v1"

  backend2:
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend2.rule=Host(`traefik`) && PathPrefix(`/v2`)"
      - "traefik.http.routers.backend2.entrypoints=web"
      - "traefik.http.routers.backend2.middlewares=remove-v2"
      - "traefik.http.middlewares.remove-v2.stripprefix.prefixes=/v2"

  frontend:
    build: ./frontend/
    command: "'sleep 3; curl traefik:8090/v1/hello; curl traefik:8090/v2/hello'"
